@startuml
title Интеграция систем банка "Стандарт" (депозиты и кредиты)

actor Клиент as Client
actor "Сотрудник отделения\n(фронт-офис)" as Front
actor "Оператор кол-центра" as CCOp
actor "Оператор партнёрского КЦ" as PCCOp
actor "Бэк-офис депозитов" as DepBO
actor "Отдел кредитования" as CredBO

package "Каналы обслуживания" {
  [Сайт банка] as Site
  [Интернет-банк] as Ibank
  [Система кол-центра] as CC
  [Внешняя система партнёрского КЦ] as PCC
}

package "Банковские системы" {
  [АБС] as ABS
  [Кредитный конвейер] as Conv
  [Скоринговая система] as Scoring
}

package "Коммуникации" {
  [SMS-шлюз] as SMS
  [Почта (e-mail)] as Mail
}

package "Модели и файлы" {
  [Excel-модель ставок\n(депозиты)] as Excel
}

cloud "Внешние сервисы" {
  [Бюро кредитных историй\n(БКИ)] as BKI
}

' Каналы и клиенты
Client --> Site : просмотр условий\nдепозитов/кредитов
Client --> Ibank : платежи,\nтекущие счета
Client --> Front : визит в отделение
Client --> CCOp : звонок в кол-центр
Client --> PCCOp : звонок в партнёрский КЦ

' Кол-центр
CCOp --> CC : регистрация обращения
PCCOp --> PCC : регистрация обращения
PCC --> CC : передача обращений партнёра

CC --> ABS : обращение по депозиту/кредиту\n(онлайн/пакетно)

' Операции в отделении
Front --> ABS : заявка на депозит/кредит,\nоткрытие договора

' Депозиты: бэк-офис и ставки
DepBO --> ABS : обработка заявок\nпо депозитам
DepBO --> Excel : ввод исходных данных,\nрасчёт ставок
Excel --> DepBO : рассчитанная ставка

DepBO --> Mail : отправка ставок и запросов
Front --> Mail : запрос спецставки
CredBO --> Mail : ответ по риску/спецставке

CredBO --> ABS : просмотр данных клиента\n(кредитный риск)
Mail --> DepBO
Mail --> Front

ABS --> SMS : SMS клиенту\n(ставка, приглашение в отделение)
SMS --> Client

' Кредиты: конвейер и скоринг
Front --> ABS : заявка на кредит
ABS --> Conv : заявки по кредитам\n(выгрузка 1 раз в сутки)

CredBO --> Conv : обработка заявок
Conv --> Scoring : запрос скоринга\n(API, онлайн)

Scoring --> BKI : запрос кредитной истории\n(API, онлайн)
BKI --> Scoring : данные по истории

Scoring --> Conv : результат скоринга
Conv --> ABS : одобренные заявки,\nстатусы (1 раз в сутки)

@enduml
